#!/bin/bash

MODE="RSA"
PRODUCT_NAME="myproduct"
CONTAINER_VER="1.0"
IMAGES="qt-image-imx7s-warp-20170727120451.rootfs.ext4.gz"
FILES="sw-description sw-description.sig $IMAGES"


openssl dgst -sha256 -sign priv.pem sw-description > sw-description.sig

for i in $FILES;do
        echo $i;done | cpio -ov -H crc >  ${PRODUCT_NAME}_${CONTAINER_VER}.swu
